### PR TITLE
feat(Trie): map_tag

### LINKED ISSUE #124: 🔖 Add `Trie.map_tag`?
Suggested by @mikeshulman.

### PR DESCRIPTION
**Pull request by favonia**
Close #124.

### CODE REVIEW

**Comment by favonia** [comment]
@mikeshulman Not sure if you still want it but I am clearing the backlog...

**Comment by mikeshulman** [comment]
Hmm, at the moment I don't even remember what I wanted this for.  But maybe it'll come to me.  (-:

**Comment by favonia** [comment]
@mikeshulman I vaguely remember it's about using tags to remember precedence and this function can update all precedence at once. Maybe I should also include a version for subtrees...

**Comment by mikeshulman** [comment]
Ah, yes, I found the old email thread.

**Comment by mikeshulman** [comment]
I thought of something else I might also use this for.  And the PR looks good to me, if you're amenable to merging it.

**Pull request merged**
